/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apache.fop.graalvm;

public class App {
    private static String xmlFileName;
    private static String outputDirectory;

    public static void main(String[] args) {
        int argi = 0;
        for(;argi<args.length;argi++) {
            String arg = args[argi];
            
            if(arg.equals("--xml")) {
                argi++;
                xmlFileName = args[argi];
            } else if (arg.equals("--out")) {
                argi++;
                outputDirectory = args[argi];
            } else if (arg.equals("--help")) {
                System.err.println();
                System.err.println("--xml       The input xml file (required).");
                System.err.println("--out       The output directory (required).");
                System.err.println();
                return;
            }  
        }
        
        if (xmlFileName == null) {
            System.err.println("Input xml file is required.");
            System.exit(2);
        }
        
        if (outputDirectory == null) {
            System.err.println("Output directory is required.");
            System.exit(2);
        }
        
        Converter converter = new Converter();
        try {
            converter.runXml2Pdf_V2(xmlFileName, outputDirectory);
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
        
    }
}
