/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package apache.fop.graalvm;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void testAppHasAGreeting() {
        System.out.println("Fubar");
    }
}
